version: '2'
services:
  mnh2-app:
    image: mnh2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:postgresql://mnh2-postgresql:5432/mnh2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mnh2-postgresql:
    extends:
      file: postgresql.yml
      service: mnh2-postgresql
